### ISSUE TITLE
Type Mismatch Error for the same type

### ISSUE THREAD

**Issue by LightSystem** [arainko/ducktape#26]
Hi @arainko,
First of all thank you for this awesome library! It is a godsend that is helping us migrate to Scala 3 in a more painless manner 😌 

I've just started using it for some of our case class transformations and have encountered a curious issue. Seems to have to do with companion objects or objects in general.
Let's imagine I have these case classes:
```
case class A(anotherCaseClass: AnotherCaseClass)
object A:
  case class AnotherCaseClass(name: String)
  case class B(anotherCaseClass: AnotherCaseClass)
```
`AnotherCaseClass` can be simple or complex, it doesn't matter. If I then do:
```
val a = A(AnotherCaseClass("test"))
a.to[B]
```
I get the following compilation error:
```
[error] -- [E007] Type Mismatch Error: /some/file:95:11 
[error] 95 |    a.to[B]
[error]    |           ^
[error]    |           Found:    A.AnotherCaseClass | dest
[error]    |           Required: A.AnotherCaseClass
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from LiftTransformationModule.scala:15
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from LiftTransformationModule.scala:15
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from LiftTransformationModule.scala:15
```
I'm using scala `3.2.1` and ducktape version `0.1.1`.

Thanks again. If I get some time I'll try to research this problem deeper by looking into ducktape's codebase though metaprogramming is something I'm not very familiar with yet.

**Comment by arainko** [comment]
Hey @LightSystem! Thanks for reporting the issue and sorry for the inconvenience that it causes! 

I can reproduce it locally and will be taking a closer look at it in the following days, in the meantime a workaround (you probably figured it out already but I'm putting it out there in case someone also stumbles upon this) is to move out the definition of `AnotherCaseClass` out of the companion object of `A`, so the code would look like this:

```scala
case class A(anotherCaseClass: AnotherCaseClass)
case class AnotherCaseClass(name: String)

object A:
  case class B(anotherCaseClass: AnotherCaseClass)
```

**Comment by arainko** [comment]
Some further findings:

It turns out that if you refer to `SomeOtherClass` as `A.SomeOtherClass` in `B`, like this:

```scala
case class A(anotherCaseClass: A.AnotherCaseClass)

object A {
  case class AnotherCaseClass(name: String)
  case class B(anotherCaseClass: A.AnotherCaseClass)
}
```

it's all fine and dandy, but once you get rid of the `A.` prefix in `B` it goes back to being broken. Feels like I'm taking crazy pills.

**Comment by arainko** [comment]
Managed to pinpoint the cause and resolve the issue, more details in #27. Once again thanks for using the library and reporting the issue @LightSystem!
