### ISSUE TITLE
Allow merging case classes

### ISSUE THREAD

**Issue by jdsalchow** [arainko/ducktape#32]
I hope I didn't miss a way of doing this already, but it would be great if there was a possibility to merge case classes.

Example:
```
case class Person(name: String)
case class Address(street: String)
case class PersonWithAddress(name: String, street: String)

Person("John von Neumann")
  .into[PersonWithAddress]
  .transform(Fields.from(Address("1 Einstein Drive")))
```

**Comment by arainko** [comment]
Hey @jdsalchow! There's no way to do that yet, I might look into implementing something like that once  I've got some spare time - no promises or ETAs on that tho! 😄

**Comment by jdsalchow** [comment]
Awesome, thanks! Can't wait for ducktype 0.1.3 😇

**Comment by arainko** [comment]
It's on its way to Maven Central as we speak :grin:
