### ISSUE TITLE
Fail when repeatedly applying configurations to the same field instead of using the last one

### ISSUE THREAD

**Issue by saeltz** [arainko/ducktape#40]
If possible, I'd prefer this to throw a compilation error. That'd be easier to debug.

I could help with this once #38 is merged.

**Comment by arainko** [comment]
yeah, this is much more sane than the current behavior which I, admittedly, parroted from chimney without giving it much thought

**Comment by arainko** [comment]
After some time thinking about it, maybe instead of erroring out we slap a `report.warn` - if a user has fatal warnings enabled that'll still fail the compile but at the same time it can be suppressed with a `@nowarn` because I believe there might be a use case or two where this behavior is desired
