### ISSUE TITLE
Ambiguous given instances for Option coproduct

### ISSUE THREAD

**Issue by PawelJ-PL** [arainko/ducktape#60]
Hi,

I'm unable to transform from case class Option to another case class Option (for example `Option[ClassA] -> Option[ClassB]`). Compilation fails with error: 

```
[error] 20 |  val b = a.to[Option[Yyy]]
[error]    |                           ^
[error]    |Ambiguous given instances: both given instance betweenOptions in object Transformer and given instance betweenCoproducts in object Transformer match type io.github.arainko.ducktape.Transformer[Option[web.Main.Xxx], 
[error]    |  Option[web.Main.Yyy]
[error]    |] of parameter x$2 of method to in package io.github.arainko.ducktape
```

Example code:
https://scastie.scala-lang.org/9z8Pyt5fSNGZdNRkY2Dv3g

**Comment by arainko** [comment]
Hey! Thanks for the report 😄 
Yeah, looks like I've messed up by not deprioritazing derived instances - should be an easy fix.
