### ISSUE TITLE
betweenMaps?

### ISSUE THREAD

**Issue by benjamingeer** [arainko/ducktape#64]
It's great that ducktape has built-in support for collections, but it looks like this doesn't work for `Map[K, V]`. I needed to validate both the keys and the values of a `Map` using an accumulating transformer, so I implemented this as a special case, but I'm guessing that there might be a more generic way to do it by considering the `Map` as a collection of tuples. Is there any chance you might add support for this?

**Comment by arainko** [comment]
oh, that's just an omission on my side - I'll add it ASAP :smile:
